version: 2
jobs:
  build:
    docker:
      - image: nullworks/cathook-docker-ci-arch:latest
    steps:
      - checkout
      - run:
          name: "Compiling Rosnehook"
          command: git submodule update --init --recursive; mkdir build; cd build; cmake
            -DEnableWarnings=0 ..; make -j8; cd ..
    # The resource_class feature allows configuring CPU and RAM resources for each job. Different resource classes are available for different executors. https://circleci.com/docs/2.0/configuration-reference/#resourceclass
    resource_class: large
  textmode_build:
    docker:
      - image: nullworks/cathook-docker-ci-arch:latest
    steps:
      - checkout
      - run:
          name: "Compiling textmode Rosnehook"
          command: git submodule update --init --recursive; mkdir build; cd build; cmake
            -DCMAKE_BUILD_TYPE=Release -DVisuals_DrawType="Textmode"
            -DVACBypass=1 -DEnableWarnings=0 ..; make -j8; cd ..
